### ISSUE TITLE
Reference and theory

### ISSUE THREAD

**Issue by benoitpaillard** [Gunnstein/fatpack#1]
Thanks a lot for the great and easy to use tool!
I'm looking for references for the different endurance curve you're using, and even though you mention EC9, I'm trying to find something a bit more simple than a complete eurocode document.
Apart from that it's working great on pandas timeseries, making it a great tool for simulation analysis.
Cheers !

**Comment by Gunnstein** [comment]
Hey @benoitpaillard ,

I am glad to hear that you found the package useful! 

Pretty much any textbook on fatigue of materials contains a chapter on endurance curves  (you may also find them under the name SN-curves or fatigue strength). I suggest the following resources (and the references therein):

- [A fatigue primer for structural engineers](https://www.aisc.org/globalassets/nsba/technical-documents/a-fatigure-primer-for-structural-engineers.pdf) is a  short, free and accessible introduction to fatigue structures and use of endurance curves in design and fatigue life assessment. See especially chapter 4.3 which discusses fatigue limits.

- [Fatigue of Structures and Materials.](https://www.springer.com/us/book/9781402068072), by Jaap Schijve is a more complete reference. Chapter 2, 6 and 7 gives a good explanation of the fatigue phenomenon and background for the knee-points in bi and trilinear endurance curves. 

If you are looking for a specific reference to data on fatigue endurance curves, you typically find them in standards, e.g. Eurocode, DNV or the american equivalents, but you also find research articles or books that may be suitable to your specific application. 

I would like to point out that you do not need to read the complete eurocode document, [Eurocode 3-1-9](https://www.phd.eng.br/wp-content/uploads/2015/12/en.1993.1.9.2005-1.pdf) is a part of the eurocode (roughly 40 pages) with fatigue curves for many different structural details.  


I hope these references are what you are looking for!

Best regards,
Gunnstein

**Comment by benoitpaillard** [comment]
Damn that's great ! Thanks a lot for all that. I believe it should go to the readme section !

Cheers, closing.

**Comment by Gunnstein** [comment]
Reopened and pinned, similar question/issue is raised in #4.
