### ISSUE TITLE
SN Array instead of Sc

### ISSUE THREAD

**Issue by rKila** [Gunnstein/fatpack#11]
Hello, I was wondering if you have a suggestion on a quick way to import own array of SN values (SN curve from test or from a simulation of a notch). I am familiar with many standards/ books that try to estimate SN curve but often enough, historic info or test data is best for damage comparison/ sensitivity bounds studies on damage and risk assessments.

**Comment by Gunnstein** [comment]
Hey,

Are you looking for a function to estimate mean or design curve from SN data, i.e. a function that takes in S and N and outputs Sc?

Best regards,
Gunnstein

**Comment by rKila** [comment]
Hello Gunnstein,
Thank you for prompt response. No I am looking for a function to use SN curve array (interpolate) without extracting the average Design Sc. This way the model can be fed straight different SN. Intent is to feed variations of SN for risk assessment/ life impact! (including SN from test/ database)

**Comment by Gunnstein** [comment]
Hey again,

If I understand correctly, you want a probability distribution for the SN curve, e.g. log Sc is normally distributed with mean mSc and std.dev sSc and the slope constant m is deterministic. 

In ASTM E739 there is a detailed description on how to estimate the mean (mSc) and std (sSc) from SN data assuming that that log Sc is normally distributed. Given this you could use repeated calls to a `scipy.stats.norm` instance to repeatedly draw realizations of Sc or a series of `k` realizations by `np.random.normal(mSc, sSc, size=k)` for use in reliability analysis.

I have used ASTM E739 myself, but I do not have a code to directly accomplish the above. 

(There is surely an alternative ISO standard as well).

Best regards,
Gunnstein
