### ISSUE TITLE
How to define a custom SN curve?

### ISSUE THREAD

**Issue by LasseLedet** [Gunnstein/fatpack#12]
How do I define a custom SN curve?

**Comment by Gunnstein** [comment]
Hey @LasseLedet,

What SN curve did you have in mind? In fatpack there are Linear, BiLinear and TriLinear SN curves implemented that can be arbitrarily customized with their parameters. See example [Defining DNVGL RP-C203 endurance curves with fatpack](https://github.com/Gunnstein/fatpack/blob/master/examples/Defining%20DNVGL%20RP-C203%20endurance%20curves%20with%20fatpack.ipynb), which shows both linear and bilinear curves defined in the DNV standard, and you can see an example of the trilinear curve, used in the Eurocode, in the example on the [frontpage](https://github.com/Gunnstein/fatpack)

Best regards,
Gunnstein

**Comment by LasseLedet** [comment]
Hi Gunnstein,

Thanks a lot for your fast reply👌

So actually I would like a BiLinear or TriLinear curve but where there is no endurance limit, so for example I’d like to a TriLinear curve where the first slope is m=3, the next is m=5 and the last is, say, m=25 (or a non-integer). Hope it makes sense 😊

 

Kind regards/Med venlig hilsen,

 

Lasse Ledet

**Comment by Gunnstein** [comment]
It is easy to achieve that, starting from the definition of [BiLinearEnduranceCurve](https://github.com/Gunnstein/fatpack/blob/b58bbfa1a7ad1a0fd6318b60a71aa96fac266f22/fatpack/endurance.py#L214), which consists of two LinearEnduranceCurve objects operating in different domains (S>Sd -> curve1 and S<=Sd -> curve2), you can just expand upon that to a third curve (with m=25) for the domain below a threshold, i.e. `S<Se` by modifying get_endurance and get_stress methods. 

The code below is working but has not been thourougly tested, check if it is what you want, test it out properly and perhaps you could incorporate into an example in a jupyter notebook and make a pull request?

```python

import fatpack
import matplotlib.pyplot as plt 

ensure_array = fatpack.endurance.ensure_array

class TrueTriLinearCurve(fatpack.BiLinearEnduranceCurve):
    Ne = 1e8
    m3 = 25
    
    @property
    def Se(self):
        return self.curve2.get_stress(self.Ne)
    
    @property
    def curve3(self):
        curve = fatpack.LinearEnduranceCurve(self.Se)
        curve.Nc = self.Ne
        curve.m = self.m3
        return curve
    
    @ensure_array
    def get_endurance(self, S):
        N = super(TrueTriLinearCurve, self).get_endurance(S)
        mask = S<self.Se
        N[mask] = self.curve3.get_endurance(S[mask])
        return N
        
    @ensure_array
    def get_stress(self, N):
        S = super(TrueTriLinearCurve, self).get_stress(N)
        mask = N>self.Ne
        S[mask] = self.curve3.get_stress(N[mask])
        return S
    
curve = TrueTriLinearCurve(90)
N = np.logspace(5, 11, 1000)
S = curve.get_stress(N)

plt.loglog(N, S)
plt.grid(which="both")
```

Best regards,
Gunnstein

**Comment by LasseLedet** [comment]
Hi Gunnstein,

Thanks a lot. It seems to work great💪💪💪

I did however have some issues with the rainflow counter which i could not match to the counting from the “rainflow” library, but it is likely because i just made a simple mistake, so no worries
________________________________
Fra: Gunnstein Thomas Frøseth ***@***.***>
Sendt: Friday, June 10, 2022 10:52:04 AM
Til: Gunnstein/fatpack ***@***.***>
Cc: LasseLedet ***@***.***>; Mention ***@***.***>
Emne: Re: [Gunnstein/fatpack] How to define a custom SN curve? (Issue #12)


It is easy to achieve that, starting from the definition of BiLinearEnduranceCurve<https://github.com/Gunnstein/fatpack/blob/b58bbfa1a7ad1a0fd6318b60a71aa96fac266f22/fatpack/endurance.py#L214>, which consists of two LinearEnduranceCurve objects operating in different domains (S>Sd -> curve1 and S<=Sd -> curve2), you can just expand upon that to a third curve (with m=25) for the domain below a threshold, i.e. S<Se by modifying get_endurance and get_stress methods.

The code below is working but has not been thourougly tested, check if it is what you want, test it out properly and perhaps you could incorporate into an example in a jupyter notebook and make a pull request for this package?

import fatpack
import matplotlib.pyplot as plt
ensure_array = fatpack.endurance.ensure_array
class TrueTriLinearCurve(fatpack.BiLinearEnduranceCurve):
    Ne = 1e8
    m3 = 25

    @property
    def Se(self):
        return self.curve2.get_stress(self.Ne)

    @property
    def curve3(self):
        curve = fatpack.LinearEnduranceCurve(self.Se)
        curve.Nc = self.Ne
        curve.m = self.m3
        return curve

    @ensure_array
    def get_endurance(self, S):
        N = super(TrueTriLinearCurve, self).get_endurance(S)
        mask = S<self.Se
        N[mask] = self.curve3.get_endurance(S[mask])
        return N

    @ensure_array
    def get_stress(self, N):
        S = super(TrueTriLinearCurve, self).get_stress(N)
        mask = N>self.Ne
        S[mask] = self.curve3.get_stress(N[mask])
        return S

curve = TrueTriLinearCurve(90)
N = np.logspace(5, 11, 1000)
S = curve.get_stress(N)

plt.loglog(N, S)
plt.grid(which="both")

Best regards,
Gunnstein

**Comment by Gunnstein** [comment]
Hey again,

I do not have much experience with the rainflow package, but perhaps you could provide the details behind the differing results such that we can understand why?

If this issue is closed, please close it appropriately. And please consider submitting a pull request with an example of the problem/solution above!

Best regards,
Gunnstein
