### ISSUE TITLE
Oscillations in mean values

### ISSUE THREAD

**Issue by abhijeet-pandey** [Gunnstein/fatpack#13]
I was trying to benchmark results from fatpack with another python package called rainflow on my sample data ([sample.txt](https://github.com/Gunnstein/fatpack/files/9466573/sample.txt)) with 64 bins in both fatpack and rainflow. Range vs cycles looks reasonable but I observed some weird behavior in fatpack cycles for mean.
![image](https://user-images.githubusercontent.com/24558167/187825132-711fdf5e-4e32-4e54-b659-2fa4ea8732bc.png)

**Python Script**
```
`
import fatpack, rainflow
import numpy as np

import matplotlib.pyplot as plt
import matplotlib.pyplot as plt

y = np.loadtxt(r"sample.txt")

S, Sm = fatpack.find_rainflow_ranges(y, return_means=True, k=64)
data_arr = np.array([Sm, S]).T
rowbins, colbins, rfcmat = fatpack.find_rainflow_matrix(data_arr, 64, 64, return_bins=True)

rowbins = 0.5 * (rowbins[:-1] + rowbins[1:]) # get mid points 
colbins = 0.5 * (colbins[:-1] + colbins[1:]) # get mid points 

ranges = []
means = []
counts = []

for range_, mean_, count, *_ in rainflow.extract_cycles(y):
    ranges.append(range_)
    means.append(mean_)
    counts.append(count)

import numpy as np

matrix = np.histogram2d(x=ranges, y=means, bins = 64, weights=counts)
rnges = 0.5 * (matrix[1][:-1] + matrix[1][1:])
men = 0.5 * (matrix[2][:-1] + matrix[2][1:])

plt.close('all')
plt.rcParams['font.size'] = 12
fig, (ax1,ax2) = plt.subplots(2,1)
ax1.plot(colbins, np.sum(rfcmat, axis = 0), label = 'fatpack')
ax1.plot(rnges, np.sum(matrix[0], axis = 1), label = 'rainflow')
ax1.set_title('Range vs Cycles')
ax1.set_ylabel('Range')
ax1.set_xlabel('Cycles')
ax1.grid()
ax1.legend()

ax2.plot(rowbins, np.sum(rfcmat, axis = 1), label = 'fatpack')
ax2.plot(men, np.sum(matrix[0], axis = 0), label = 'rainflow')
ax2.set_title('Mean vs Cycles')
ax2.set_xlabel('Mean')
ax2.set_ylabel('Cycles')
ax2.legend()
ax2.grid()
plt.tight_layout()
`
```

**Comment by Gunnstein** [comment]
Dear @abhijeet-pandey,

Try increasing the discretization paramter `k` in `fatpack.find_rainflow_ranges` to a higher value, e.g.  `S, Sm =  fatpack.find_rainflow_ranges(y, return_means=True, k=2**14)`. 

Check reply:https://github.com/Gunnstein/fatpack/issues/6#issuecomment-602685170 for explanation of this parameter, it is perhaps time to increase the default value to reflect modern computing power and accuracy reqiurements.

Best regards,
Gunnstein

**Comment by Gunnstein** [comment]
Dear @abhijeet-pandey,

By increasing ´k´ you will find that the resulting range, mean distributions are practically identical, with some small difference. 

Furthermore, if you establish the rainflow matrix with the same approach for both packages, e.g. using `np.histogram2d`  instead of `fatpack.find_rainflow_matrix` function, you will likely find identical results between the two packages.

Best regards,
Gunnstein

**Comment by abhijeet-pandey** [comment]
Thank you very much, that solves that!
