### ISSUE TITLE
Rainflow count on a dataseries with repetitions

### ISSUE THREAD

**Issue by MLipcan** [Gunnstein/fatpack#18]
Dear Thomas,
thank for the package. It is very helpful and a good starting point on timeseries fatigue calculation.
My use-case of the package is in wind turbine engineering to retrieve the Markov matrices and damage equivalent values of several dataseries which are combined with a single repetitions file giving the occurrence number of each dataseries within a representative lifetime.

For the use-case wind turbines, the lifetime fatigue loads are given by a set of dataseries and a file giving the number of occurrences for each of these dataseries during the turbines lifetime:

> #filename; occurrences
> dataseries_1; n
> dataseries_2; m

My approach is to calculate the ranges per file and add a third column giving the occurrence of each row and aggregate the ranges from all dataseries in one array:

> #range; rean; occurrence
> S_i_dataseries_1; S_m_j_dataseries_1; n
> S_j_dataseries_2; S_m_j_dataseries_2; m

Now, how to get the representative Markov Matrix for all dataseries and their respective occurrences?

My guess on how to incorporate this would be directly at the function "find_rainflow_matrix()" of  "rainflow.py". 
![image](https://user-images.githubusercontent.com/20436116/223994409-373b5b7f-276c-42a4-8137-4853b051ef65.png)

Does this make sense to add as a feature or capability to the code itself or can this already be solved with the present release?
Thank you very much!

Cheers, 
Max

**Comment by Gunnstein** [comment]
Dear @MLipcan (Max),

Glad to hear that you find the package useful!

> Does this make sense to add as a feature or capability to the code itself or can this already be solved with the present release?

Unfortunately, there is no elegant way to solve this in the present implementation. But, this feature should absolutely be incorporated in the package, I've had several use cases for it myself.

The suggestion you have will achieve what you aim for. However, for some time I have wanted to change the signature of the function and the implementation. You can actually achieve virtually the same result with a single function call to `numpy.histogram2d`:

`rfcmat, _, _ =numpy.histogram2d(S, Sm, [bins_S, bins_Sm], weights=occurences)`

This approach avoids joining `S` and `Sm` into a `data_array` (typically `data_array = np.array([S, Sm]).T`) which is necessary in the current `find_rainflow_matrix` implementation and is also likely more efficient. 

Perhaps you could implement the change and make a pull request?


Best regards,
Gunnstein

**Comment by Gunnstein** [comment]
Dear @MLipcan,

I decided to implement it myself, in version 0.7.4 the option `counts` can be used to include occurences, i.e. the call is now `rfcmat = fatpack.find_rainflow_matrix(data_array, rowbins, colbins, counts=occurences)`

Best regards,
Gunnstein
