### ISSUE TITLE
Adding fatpack to conda-forge

### ISSUE THREAD

**Issue by gbarter** [Gunnstein/fatpack#20]
Many thanks to @Gunnstein for creating such a helpful python package.  The NREL team has been using it more and more and we would like to add it to the conda-forge ecosystem.  I have done the initial effort to make that happen and am looking for the blessing from the core team to push ahead.  `gunnstein` has been added to the list of feedstock maintainers, of course.  See the pending PR [here](https://github.com/conda-forge/staged-recipes/pull/22661).

**Comment by Gunnstein** [comment]
Dear @gbarter,

I am very happy to hear that you and you team finds the package useful!

Adding fatpack to conda has been on my to-do list, thanks for making it happen. I have also confirmed my willingness to maintain the conda recipe.

Best regards,
Gunnstein
