### ISSUE TITLE
add min max for load class boundaries

### ISSUE THREAD

**Issue by sfreund-DLR** [Gunnstein/fatpack#22]
when calculating some fatigue characteristics of a load set using fatpack.rainflow and one wants to calculcate intermediate steps using just a slice of the load set, then the load class boundaries vary. This is due to the absolute min/max values might not be in the slice of the given load set. Example:

![Figure_1](https://github.com/Gunnstein/fatpack/assets/24474292/901e748d-848b-48ad-a129-19e555dc3a05)

The unsteady steps at approx 2.5E7 and 4.8E7 result from a shift in the values of ymin or ymax in fatpack.rainflow.get_load_class_boundaries(). 

Thus, ymin and ymax are introduced as optional parameters. Result:

![Figure_2](https://github.com/Gunnstein/fatpack/assets/24474292/9e5ad224-974a-43bf-9ff4-11a94c00635f)

**Comment by Gunnstein** [comment]
Thank you for implementing this, merged!
