### ISSUE TITLE
Incompatible with numpy 2.0

### ISSUE THREAD

**Issue by greschd** [Gunnstein/fatpack#24]
Hi! Thanks for writing this library.

The recent release of numpy 2.0.0 has removed the `asfarray` function, used here (https://numpy.org/doc/stable/release/2.0.0-notes.html#numpy-2-0-python-api-removals). I believe the correct replacement may be `np.asarray(..., dtype=np.double)`, although I'm not completely certain on the correct dtype.

I have also not checked whether other now-removed numpy functions are also used.

Happy to create a PR if that's desired.

**Comment by Gunnstein** [comment]
Hey,

I would greatly appreciate a pull request!

Best regards,
Gunnstein

**Comment by Gunnstein** [comment]
Hey again,

Good work! 

For future reference, there is a test suite with almost complete coverage that ensures code is working properly. It is based on the unittest module that is available in the standard library. You can run the test suite with your environment by opening a terminal in the base folder (folder alongside pyproject.toml) and executing the command `python -m unittest discover`.  Automatic testing with python 2.7 and python 3 can be done with `tox` (after installing tox with `pip install tox`) aswell.

I have run the tests on your branch with both python2.7 and python3 and everything is working. I will therefore accept the pull request.

Best regards,
Gunnstein
