### ISSUE TITLE
Numpy asfarray was removed in numpy 2.0

### ISSUE THREAD

**Issue by JamesIsCooke** [Gunnstein/fatpack#26]
When running:
curve.find_miner_sum(S)
line 126, in find_miner_sum
    Sr = np.asfarray(S)

AttributeError: `np.asfarray` was removed in the NumPy 2.0 release. Use `np.asarray` with a proper dtype instead.

**Comment by greschd** [comment]
This was fixed in #25, but the change has not been released. @Gunnstein could you maybe create a release including this change?
This would also help us out, as we'll otherwise have to (eventually) switch to installing from the `master` branch.

**Comment by Gunnstein** [comment]
Hey,

I have just made a new release and published version v0.7.8 on PyPI, such that you can upgrade your install with: `pip install fatpack -U`

Best regards,
Gunnstein

**Comment by JamesIsCooke** [comment]
Thank you!

**Comment by greschd** [comment]
Fantastic, thank you!
