### ISSUE TITLE
Looking forward to getting your papers

### ISSUE THREAD

**Issue by yuhanghanghang** [Gunnstein/fatpack#27]
Hello:
May I ask if I can get your paper or literature that you find useful? If I can use them, they will be of great help to me. Looking forward to your reply.
Email: 3121282348@qq.com

**Comment by Gunnstein** [comment]
Hey, 

I am unsure what literature you are looking for, but perhaps you find the answer to a prior issue useful: #1 

Gunnstein

**Comment by Gunnstein** [comment]
Hey,

Was the literature referenced above what you were looking for? 

Please close this issue if you are satsified.

Best regards,
Gunnstein
