### ISSUE TITLE
A little distance between reversals and peaks(valleys)

### ISSUE THREAD

**Issue by The-Hierophant** [Gunnstein/fatpack#6]
There is a little distance (about 5 in my example) between reversals and peaks (valleys), whether or not filtered.

Is it normal? Shall I do something to reduce the deviation?

code:

```python
import numpy as np
import matplotlib.pyplot as plt
import fatpack

plt.rcParams['figure.figsize'] = (10, 5)
plt.rcParams['grid.linestyle'] = "--"
plt.rcParams['axes.grid'] = True


def reversals(data, draw=False, filterrange=0.0):
    rev = fatpack.find_reversals(data[0])
    if filterrange < 1.0e-9:
        x, ix = rev
    else:
        x, ix = fatpack.find_reversals_racetrack_filtered(data[0], filterrange)
    if draw:
        plt.plot(data[0], color="black", label='original data')
        plt.plot(ix, x, 'ro', fillstyle='none', label='reversals')
        plt.axis([0, 10000, -0.045, 0.045])
        plt.show()
    return x


if __name__ == '__main__':
    response = np.load('response.npy', allow_pickle=True)
    reversals(response, True)
    reversals(response, True, 0.0001)
    print()

```

output:

![image](https://user-images.githubusercontent.com/45378227/77308943-b9239580-6d36-11ea-975e-e89e16ba82ee.png)

![image](https://user-images.githubusercontent.com/45378227/77308969-c6d91b00-6d36-11ea-9bc8-b818cf9fdd1c.png)

response.npy:

[response.zip](https://github.com/Gunnstein/fatpack/files/4368406/response.zip)

**Comment by Gunnstein** [comment]
Hey @The-Hierophant,

I am reluctant to open the npy file with allow_pickle due to the possibility of [malicious code](https://wiki.python.org/moin/UsingPickle). 

What do you mean by distance? Is it shift in index and/or peak? Could you try changing the number of intervals `k` to something higher e.g. `k=2**12`

```python
fatpack.find_reversals_racetrack_filtered(data[0], filterrange, k=2**12)
```

and 

```python
fatpack.find_reversals_racetrack_filtered(data[0], filterrange, k=2**12)
```

**Comment by The-Hierophant** [comment]
Hey @Gunnstein , thank you for your reply.

Here is the npy file without allow_pickle:

[response.zip](https://github.com/Gunnstein/fatpack/files/4369512/response.zip)

What I want to say is that the calculated reversals are not exactly at the peaks (or valleys).

![image](https://user-images.githubusercontent.com/45378227/77321599-60abc280-6d4d-11ea-9f89-111cb4a52c24.png)

It looks fine now after adding the `k=2**12`.

![image](https://user-images.githubusercontent.com/45378227/77321924-e2035500-6d4d-11ea-948d-324db7c6e573.png)

![image](https://user-images.githubusercontent.com/45378227/77322739-2511f800-6d4f-11ea-919d-6e41e55978f6.png)

So what is the meaning of `k` and how to choose the value of it?

Thanks.

**Comment by Gunnstein** [comment]
This is well explained in the references given in [rainflow.py](https://github.com/Gunnstein/fatpack/blob/master/fatpack/rainflow.py).

**What is the meaning of k?**
k+1 is the number of intervals that the full range (min-max) of the signal is classified into before finding reversals. If 20 is the maximum, -20 is the minimum and k=4, the interval mean values are at (-20, -10, 0, 10, 20). All data points in the signal will then be rounded to the mean value of the interval, e.g. a 6 will be rounded to 10, a -11 will be rounded to -10 and so on. This effectively removes reversals with small cycles from the signal and reduces the memory and cpu requirements of the algorithm (which was important back in the 80s and 90s). If k is large enough, this discretization error is negligible in comparison to measurement/model/modeling errors found elsewhere in the (fatigue) analysis.

**Which value should you choose?** 
The standard practice among researchers and practitioners in industry (at least during that time) was to take k=64, see pg 287 in Amzallag et.al 1994. This is also the reason for selecting k=64 as the default value in fatpack.  

Today we have an abundance of computing power and memory. For most signals and applications, you can set k as large as you like without any computational issue.  Setting k higher will strictly speaking be more accurate. If you are satisfied with the results, use k=2**12=4096 or try setting it smaller until you are not.

Best regards,
Gunnstein

**Comment by The-Hierophant** [comment]
I understand, thank you for your explanation.
