### ISSUE TITLE
Large Damage on Miner's Rule

### ISSUE THREAD

**Issue by Bibsrabelo** [Gunnstein/fatpack#8]
Hi, the signal I'm using is the one below and as you can see the pressure isn't even in MPa:

![Captura de Tela 2021-09-22 às 01 13 17](https://user-images.githubusercontent.com/56843975/134282443-8eaf7b9d-af36-4b9c-aaee-139425320b43.png)

Despite this fact, when I apply the `find_miner_sum` function I get this:
![Captura de Tela 2021-09-22 às 01 17 02](https://user-images.githubusercontent.com/56843975/134282729-e140a568-aa87-4553-9335-5bbba8e2ce4a.png)

I would like to state that I'm new at this subject and I thought only pressures in MPa would cause damage to the equipment, so my question is: Is this value possible or normal to find for pressure values like these? Because if a value such as 1.62E+01 is true then the equipment would pretty damaged.

**Comment by Gunnstein** [comment]
Dear @Bibsrabelo ,

You partially answered the question; one must use consistent units on the loads and the endurance. 

In the provided example you have defined the loads in Pa and the characteristic stress in the endurance is then also interpreted in units of Pa. Comparing the dominating stress range in you loads (40000 Pa) to the characteristic stress of the endurance curve of 160 Pa it is no wonder the example yields such high damage. 

Change the load (pressure) to MPa or the characteristic stress in your endurance curve to Pa and you will have damage that is of the correct order of magnitude. 

Best regards,
Gunnstein

**Comment by Gunnstein** [comment]
Dear @Bibsrabelo, 

Have this issue been resolved? If so, please remember to close the issue.

Since you are new to the subject, you may also find issue #1 useful.

Best regards,
Gunnstein

**Comment by Bibsrabelo** [comment]
Oh, I'm sorry...didn't know I had to do that. It was my first time asking a question on GitHub. Thanks for the help.
